---
title: "Bericht (für Fachkolleg:innen)"
author: "Moritz Laßnig, Moritz Schrom, Claudia Vötter"
date: "4\\. Dezember 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ausgangssituation

Die Tierkreiszeichen (im Allgemeinen vereinfacht Sternzeichen genannt) beschreiben zwölf gleich große Abschnitte im Tierkreis, einer 20 Grad breiten Zone um die Ekliptik (scheinbare Sonnenbahn). Sie werden noch heute häufig in der Astrologie für z.B. Horoskope verwendet, und spalten damit die Meinungen, ob durch sie valide Prognosen gestellt werden können. In dieser Kontroverse gründet die Motivation unserer Forschung, um dem oft sehr emotional geführten Diskurs ein empirisch untermauertes Argument hinzuzufügen.

**Forschungsfrage**: Gibt es einen Zusammenhang zwischen dem Sternzeichen einer Person und ihren Charaktereigenschaften?

**Forschungshypothese**: In vergleichbaren Gruppen von Menschen mit demselben Sternzeichen wird eine Gruppe eine stärkere oder schwächere Ausprägung einer Charaktereigenschaft aufweisen.

**Nullhypothese**: Es gibt keine signifikanten Unterschiede in den beobachteten Charaktereigenschaften zwischen vergleichbaren Gruppen von Menschen mit demselben Sternzeichen. Sternzeichen und Charaktereigenschaften sind unabhängig.

**Alternativhypothese**: Es gibt signifikante Unterschiede in beobachteten Charaktereigenschaft zwischen vergleichbaren Gruppen von Menschen mit demselben Sternzeichen. Zumindest eine Charaktereigenschaft ist bei zumindest einer Gruppe besonders stark oder schwach ausgeprägt. Sternzeichen und Charaktereigenschaft sind abhängig.

Es handelt sich hierbei um eine *vorhersagende Forschungsfrage*, da untersucht wird was passiert, wenn sich eine Variable (Sternzeichen) ändert. Es wird die Beeinflussung dieser Variable auf die zweite Variable (Charaktereigenschaft) untersucht. Dazu werden Daten erhoben, mit welcher die Hypothese getestet wird.

Des Weiteren handelt es sich um eine *korrelative Forschungshypothese*, da nur ein möglicher Zusammenhang zwischen den Variablen (welcher zum Beispiel in Form eines Modells für Prognosen verwendet werden könnte) wird. Unsere Forschungshypothese zielt nicht darauf ab einen kausalen Zusammenhang zwischen dem Sternzeichen und Charaktereigenschaft zu be- oder wiederlegen.

Für die Charaktereigenschaften einer Person gibt es viele potenzielle Störfaktoren. Zum Beispiel die Sozialisation der Person, welche eine Anpassung an gesellschaftliche Denk- und Gefühlsmuster durch Verinnerlichung von sozialen Normen beschreibt. Wichtige Beiträge für die Erforschung der Entwicklung von Persönlichkeitsmerkmalen in der frühen Kindheit, Jugend bis hin zum mittleren und höheren Lebensalter (daher über die gesamte Lebensspanne) kommen vor allem aus Humangenetik, Entwicklungsbiologie, Ethnologie und Kulturanthropologie, sowie aus sonstigen Arbeitsrichtungen der Psychologie. Für unsere konkrete Forschungshypothese hat dies jedoch keinen direkten Einfluss, da davon auszugehen ist, dass sich Störfaktoren auf die Gesamtheit auswirken, und nicht nur auf eine Gruppe mit einem Sternzeichen. Auf mögliche Störfaktoren, welche erwartete Verteilungen der Ausprägungen beeinflussen, wird in der deskriptiven Analyse genauer eingegangen.
Ein weiterer Störfaktor ist die Person, welche die Daten erhebt. Um dies zu erläutern, wird im folgenden kurz auf die Methode der Datenerhebung und das Forschungsdesign im Allgemeinen eingegangen.

## Forschungsdesign
Für die Beantwortung der Forschungsfrage wurden Daten von den Autor:innen gesammelt. Um Unschärfen in der Selbsteinschätzung zu verhindern, bewerteten die Autor:innen Personen aus dem Umfeld nach den Myers-Briggs Typenindikatoren. Es handelt sich dabei um vier binären Kategorien, welche unterschiedliche Charaktereigenschaften von Menschen kategorisieren. Zusätzlich wurde der Geburtstag (Tag und Monat) erfasst. Die Erfassung wurde in einer für alle Autor:innen zugänglichen geschützten Datenbank durchgeführt. Da es sich hierbei am Ende des Tages um eine subjektive Einschätzung handelt, ist die einschätzende Person ein potenzieller Störfaktor. Um diesen Störfaktor auszugleichen, wurde von allen Autor:innen gleichermaßen zum Datensatz beigetragen. Dies gleicht auch Unterschiede im Umfeld der erhebenden Personen aus. Eine weitere Fehlerquelle sind Doppelerfassungen im Datensatz. Da sich der Bekanntenkreis der Autor:innen sich kaum überlappt, und aktiv darauf geachtet wurde keine Duplikate zu erfassen, stellt dies nach Meinung der Autor:innen jedoch kein Problem dar.

Zwar wird von keinen signifikanten Unterschieden vom Einfluss (oder Nicht-Einfluss) von Sternzeichen auf Charaktereigenschaft in unterschiedlichen Altersgruppen und sozialen Kreisen ausgegangen, jedoch ist dies zum aktuellen Stand nicht empirisch belegt. Daher können wir nur von einer Grundpopulation ausgehen, für welche die Stichprobe repräsentativ ist. Es handelt sich bei den erfassten Personen um größtenteils österreichische Student:innen oder Akademiker:innen im Alter von 20-35 Jahren. Um schnelle und falsche Schlüsse auf eine zu große Grundgesamtheit bei unserem Stichprobenumfang zu vermeiden, bezieht sich die Grundpopulation auf genau ebendiesen beschriebenen Personenkreis.

## Operationalisierung

\textcolor{red}{Wie bereits allgemein beschrieben, werden Informationen zum Sternzeichen und zu den Charaktereigenschaften von Personen nach dem Myers-Briggs Typenindikator mit Hilfe einer geteilten Datenbank gesammelt. Im konkreten bedeutet dies, dass primär folgende Variablen mit den genannten Ausprägungsformen erfasst werden:}

* \textcolor{red}{Geburtsdatum (Tag und Monat, z.B. 04.11.)}
* \textcolor{red}{Charaktereigenschaften:}
  * \textcolor{red}{Extraversion / Introversion}
  * \textcolor{red}{Intuition / Sensorik}
  * \textcolor{red}{Denken / Fühlen}
  * \textcolor{red}{Wahrnehmen / Beurteilen}

\textcolor{red}{Es handelt sich bei den vier Merkmalen welche die Charaktereigenschaften von Personen beschreiben jeweils um kategoriale Variablen mit binärer Ausprägung: Jede der vier Kategorien wird in zwei mögliche Ausprägungen unterteilt. So kann die Variable "Extraversion / Introversion" entweder den Wert "Extraversion" oder "Introversion" annehmen, jedoch nie beide oder keinen der beiden möglichen Werte. Dies kann im Folgenden auch kodiert werden:}

* \textcolor{red}{Charaktereigenschaft1: Extraversion (0) ... Introversion (1)}
* \textcolor{red}{Charaktereigenschaft2: Intuition (0) ... Sensorik (1)}
* \textcolor{red}{Charaktereigenschaft3: Denken (0) ... Fühlen (1)}
* \textcolor{red}{Charaktereigenschaft4: Wahrnehmen (0) ... Beurteilen (1)}

\textcolor{red}{In der Datenerfassung wird ein verpflichtendes Auswahlfeld verwendet, welches den Wertebereich auf die beschriebenen binären Ausprägungen einschränkt.}

\textcolor{red}{Beim Geburtsdatum handelt es sich um ein verpflichtendes Datumsfeld, welches den Wertebereich auf gültige Tages und Monatswerte festlegt. Im folgenden wird aus dem Geburtsdatum das Tierkreiszeichen abgeileitet. Da das Geburtsjahr für die Bestimmung des Tierkreiszeichens nicht notwendig ist, wird dieses nicht erfasst.}

\textcolor{red}{Es handelt sich beim Tierkreiszeichen um eine kategoriale Variable, mit zwölf möglichen Ausprägungen:}

* \textcolor{red}{Widder (21.03. - 20.04.)}
* \textcolor{red}{Stier (21.04. - 21.05.)}
* \textcolor{red}{Zwillinge (22.05. - 21.06.)}
* \textcolor{red}{Krebs (22.06. - 22.07.)}
* \textcolor{red}{Löwe (23.07. - 22.08.)}
* \textcolor{red}{Jungfrau (23.08. - 22.09.)}
* \textcolor{red}{Waage (23.09. - 22.10.)}
* \textcolor{red}{Skorpion (23.10. - 22.11.)}
* \textcolor{red}{Schütze (23.11. - 20.12.)}
* \textcolor{red}{Steinbock (21.12. - 19.01.)}
* \textcolor{red}{Wassermann (20.01. - 18.02.)}
* \textcolor{red}{Fische (19.02. - 20.03.)}

\textcolor{red}{Um den Datensatz auch hinsichtlich möglichen Störvariablen zu untersuchen, werden außerdem folgende Metadaten erfasst:}

* \textcolor{red}{Erfassende Person (Freitextfeld welcher mit dem Namen der erfassenden Person befüllt wird, in unserem Fall der Vor- und Nachname einer der drei Autor:innen)}
* \textcolor{red}{Erfassungsdatum (Tag, Monat und Jahr, z.B. 09.01.2023)}

## Statistische Methoden



# Beschreibung des Datensatzes ("Datensteckbrief")

* Stichprobenumfang
* Merkmale (samt Skalenniveau)
* Gibt es fehlende Werte? Wir wurden diese behandelt?

# Ziel der Analyse (Kurz, nicht ganze Angabe abschreiben)

# Deskriptive Analyse der Stichprobe

* Diagramm(e) samt Beschreibungen: Gibt es Auffälligkeiten?
* Tabellen, Kennzahlen ... samt verbaler Beurteilung
* Ableitung allfälliger Hypothesen

# Überprüfung der Fragestellung bzgl. der Grundgesamtheit (Tests, Konfidenzintervalle, Modelle etc.)

* Bei Tests:
  * Angabe von Testbezeichnung
  * Begründung der Testauswahl (z.B. robuste Methoden bei Ausreißern etc.)
  * Null- und Alternativhypothese
  * Signifikanzniveau
  * P-Wert
  * Formale Schlussfolgerung (Vergleich P-Wert mit Signifikanzniveau)
  * Inhaltliche Schlussfolgerung
* Bei Modellen:
  * Begründung für die Wahl des Modells (z.B. abhängig vom Skalenniveau der abhängigen und unabhängigen Variablen)
  * Schätzung des Modells
  * Bei Regressionsmodellen: Ableitung der Modellformel, sowie Interpretation des Einflusses der unabhängigen Variablen auf die abhängige Variable ("Effektstärke"). Unterstützung via Effektplot bzw. Modellplot
  * Beurteilung der Signifikanz der Parameter, sowie des Gesamtmodells
  * Beurteilung der Modellgüte (z.B. R<sup>2</sup> bei linearer Regression)
  * Modelldiagnostik (Normalverteilung der Residuen, Restzusammenhang der Residuen mit den geschätzten Werten)
  * Diagramm mit erwarteten Werten (z.B. Regressionsgerade) samt Konfidenzbändern
  * Vorhersagen (erwartete Werte, bzw. Prognoseintervalle für Einzelwerte)

# Fazit

* Zusammenfassung
* Diskussion allfälliger Probleme
* Generalisierbarkeit der Ergebnisse

\newpage

# Aufgabe 3

## Formulierung der Forschungsfrage

## Beschreibung des Forschungshintergrunds

## Formulierung der Forschungshypothese

### Art der Forschungshypothese (korrelativ/kausal)

### abhängige und unabhängige Variable (wenn sinnvoll)

### Beeinflussbarkeit der unabhängigen Variable

### Mögliche Störvariablen

## Neu: Forschungsdesign

### Erhebungsform

### Definition der Beobachtungseinheiten

### Definition der Population/Grundgesamtheit

### Stichprobenbeziehung

### Repräsentativität

\newpage

# Aufgabe 4

## Formulierung der Forschungsfrage

## Beschreibung des Forschungshintergrunds

## Formulierung der Forschungshypothese

### Art der Forschungshypothese (korrelativ/kausal)

### abhängige und unabhängige Variable (wenn sinnvoll)

### Beeinflussbarkeit der unabhängigen Variable

### Mögliche Störvariablen

## Forschungsdesign

### Erhebungsform

### Definition der Beobachtungseinheiten

### Definition der Population/Grundgesamtheit

### Stichprobenbeziehung

### Repräsentativität

## Neu: Operationalisierung

### Skalenniveau der interessierenden Variablen (inklusive Störvariable)

### Mögliche Ausprägungen (Kategorien bzw. Wertebereich)

### Für metrische Variablen: Präzision der Messungen

## Neu: Statistische Methoden

### Verwendete Methode (ohne Berücksichtigung der Störvariable)

### Verwendete Methode (bei Berücksichtigung der Störvariable)
